# Generated by Django 5.1.7 on 2025-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="journals/"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name="journal",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
