# Generated by Django 5.1.7 on 2025-04-10 17:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
